name: Build & Publish images

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  hello-world:
    name: Build & Publish
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    with:
      context: .
      cache-from: type=gha
      cache-to: type=gha,mode=max
    steps:
    - name: Build & Publish
      run: python scripts/build_and_publish.py
      shell: sh
