name: Build & Publish images

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  hello-world:
    name: Build & Publish
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Build & Publish
      run: python scripts/build_and_publish.py
      shell: sh
