name: Build & Publish images

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  hello-world:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & Publish
      run: python scripts/build_and_publish.py
      shell: sh
