name: Build & Publish images

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  hello-world:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: checkout repo
        uses: actions/checkout@v2.3.4

      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: cache
          key: ${{ runner.os }}-cache

      - name: Build & Publish
        run: python scripts/build_and_publish.py
        shell: sh
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
